# codigos 
X = "x" 
O = "o"

# posiçoes nomeadas
LINHAS = {
    "SUP": 0,
    "MEIO": 1,
    "INF": 2,
}

COLUNAS = {
    "ESQ": 0,
    "MEIO": 1,
    "DIR": 2
}
CANTO_SUP_ESQ = [LINHAS["SUP"], COLUNAS["ESQ"]]
CANTO_SUP_DIR = [LINHAS["SUP"], COLUNAS["DIR"]]
CANTO_INF_ESQ = [LINHAS["INF"], COLUNAS["ESQ"]]
CANTO_INF_DIR = [LINHAS["INF"], COLUNAS["DIR"]]
MEIO_SUP = [LINHAS["SUP"], COLUNAS["MEIO"]]
MEIO_INF = [LINHAS["INF"], COLUNAS["MEIO"]]
MEIO = [LINHAS["MEIO"], COLUNAS["MEIO"]]
BORDA_ESQ = [LINHAS["MEIO"], COLUNAS["ESQ"]]
BORDA_DIR = [LINHAS["MEIO"], COLUNAS["DIR"]]

CANTOS = [CANTO_SUP_DIR, CANTO_INF_ESQ, CANTO_INF_DIR, CANTO_SUP_ESQ, BORDA_DIR, BORDA_ESQ, MEIO_SUP, MEIO_INF]
# tipos de jogadores
MANUAL = 1
ALEATORIO = 2
DIFICIL = 3

# historico
ARQUIVO = "historico.txt"

forcar_meio = 1
forcar_canto = 0